# Generated by Django 6.0.2 on 2026-05-11 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('user', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('audit', 'audit'), ('finding', 'finding'), ('cap', 'cap'), ('system', 'system')], default='system', max_length=20)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=200)),
                ('lead_auditor', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed')], default='Planned', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('risk_rating', models.CharField(default='Medium', max_length=20)),
                ('scope', models.TextField(blank=True)),
                ('objectives', models.TextField(blank=True)),
                ('completion_percent', models.PositiveIntegerField(default=0)),
                ('findings_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AuditableEntity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('risk_rating', models.CharField(default='Medium', max_length=20)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=200)),
                ('action', models.CharField(max_length=255)),
                ('target', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Auditor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('availability', models.CharField(choices=[('Available', 'Available'), ('On Audit', 'On Audit'), ('On Leave', 'On Leave')], default='Available', max_length=20)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('certifications', models.JSONField(blank=True, default=list)),
                ('weekly_capacity_hours', models.PositiveIntegerField(default=40)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_id', models.CharField(db_index=True, max_length=100)),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('head', models.CharField(blank=True, max_length=200)),
                ('risk_rating', models.CharField(default='Medium', max_length=20)),
                ('last_audit_date', models.DateField(blank=True, null=True)),
                ('next_audit_date', models.DateField(blank=True, null=True)),
                ('entity_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('type', models.CharField(default='info', max_length=50)),
                ('read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentImportIssue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('error', 'error'), ('warning', 'warning'), ('info', 'info')], default='warning', max_length=20)),
                ('sheet_name', models.CharField(blank=True, max_length=255)),
                ('row_number', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentSheet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RiskHistoryEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('previous_rating', models.CharField(max_length=20)),
                ('current_rating', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AuditAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(choices=[('Planning', 'Planning'), ('Fieldwork', 'Fieldwork'), ('Reporting', 'Reporting'), ('Review', 'Review')], default='Planning', max_length=20)),
                ('allocation_pct', models.PositiveIntegerField(default=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='iams.audit')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='iams.auditor')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('assignee', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='iams.audit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('size_kb', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
                ('uploaded_at', models.DateTimeField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_files', to='iams.audit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=200)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('root_cause', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='iams.audit')),
            ],
            options={
                'ordering': ['-due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='CorrectiveAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('In Progress', 'In Progress'), ('Overdue', 'Overdue'), ('Closed', 'Closed')], default='Open', max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('progress', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(max_length=200)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrective_actions', to='iams.finding')),
            ],
            options={
                'ordering': ['-due_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='FollowUpItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('finding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='iams.finding')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HoursBudget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budgeted_hours', models.PositiveIntegerField(default=0)),
                ('consumed_hours', models.PositiveIntegerField(default=0)),
                ('audit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hours_budget', to='iams.audit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentMatrixCell',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('likelihood', models.CharField(max_length=50)),
                ('impact', models.CharField(max_length=50)),
                ('residual_risk', models.CharField(default='Medium', max_length=20)),
            ],
            options={
                'unique_together': {('likelihood', 'impact')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_sheet', models.CharField(blank=True, max_length=255)),
                ('source_row', models.PositiveIntegerField(default=0)),
                ('department', models.CharField(max_length=200)),
                ('objective', models.TextField(blank=True)),
                ('risk_area', models.CharField(max_length=255)),
                ('risk_description', models.TextField(blank=True)),
                ('grading', models.CharField(blank=True, max_length=50)),
                ('likelihood', models.CharField(default='Medium', max_length=20)),
                ('impact', models.CharField(default='Medium', max_length=20)),
                ('inherent_risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('existing_controls', models.TextField(blank=True)),
                ('control_effectiveness', models.CharField(blank=True, max_length=50)),
                ('residual_risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=20)),
                ('audit_objective', models.TextField(blank=True)),
                ('audit_steps', models.TextField(blank=True)),
                ('documents_required', models.TextField(blank=True)),
                ('inclusion_status', models.CharField(choices=[('Included', 'Included'), ('Excluded', 'Excluded'), ('Deferred', 'Deferred')], default='Included', max_length=20)),
                ('audit_scope', models.TextField(blank=True)),
                ('planned_man_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('notes', models.TextField(blank=True)),
                ('sheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='iams.riskassessmentsheet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RiskAssessmentSummaryItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inclusion_status', models.CharField(choices=[('Included', 'Included'), ('Excluded', 'Excluded'), ('Deferred', 'Deferred')], default='Included', max_length=20)),
                ('audit_scope', models.TextField(blank=True)),
                ('planned_man_days', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_items', to='iams.riskassessmentrecord')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Submitted', 'Submitted'), ('Approved', 'Approved')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='iams.audit')),
                ('auditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='iams.auditor')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='iams.audit')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
