# Generated by Django 6.0.2 on 2026-05-11 10:28

from django.db import migrations, models


def add_evidence_file_field_if_missing(apps, schema_editor):
    """
    Make this migration idempotent for environments where the `file` column
    was added manually or by a partial prior rollout.
    """
    EvidenceFile = apps.get_model("iams", "EvidenceFile")
    table_name = EvidenceFile._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "file" in columns:
        return

    field = models.FileField(blank=True, null=True, upload_to="evidence/%Y/%m/%d/")
    field.set_attributes_from_name("file")
    schema_editor.add_field(EvidenceFile, field)


def remove_evidence_file_field_if_exists(apps, schema_editor):
    EvidenceFile = apps.get_model("iams", "EvidenceFile")
    table_name = EvidenceFile._meta.db_table

    with schema_editor.connection.cursor() as cursor:
        columns = {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor, table_name
            )
        }

    if "file" not in columns:
        return

    field = models.FileField(blank=True, null=True, upload_to="evidence/%Y/%m/%d/")
    field.set_attributes_from_name("file")
    schema_editor.remove_field(EvidenceFile, field)


class Migration(migrations.Migration):

    dependencies = [
        ('iams', '0002_activityitem_audit_auditableentity_auditlogentry_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_evidence_file_field_if_missing,
                    reverse_code=remove_evidence_file_field_if_exists,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="evidencefile",
                    name="file",
                    field=models.FileField(blank=True, null=True, upload_to="evidence/%Y/%m/%d/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
    ]
