# Generated by Django 6.0.2 on 2026-05-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iams', '0002_activityitem_audit_auditableentity_auditlogentry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evidencefile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='checklistitem',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Complete', 'Complete'), ('N/A', 'N/A')], default='Pending', max_length=20),
        ),
    ]
