# Generated by Django 6.0.2 on 2026-05-11 10:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iams', '0003_evidencefile_file_alter_checklistitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Audit Plan', 'Audit Plan'), ('Finding', 'Finding'), ('CAP Closure', 'CAP Closure'), ('Report', 'Report'), ('Risk Assessment', 'Risk Assessment')], max_length=50)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('submitted_by', models.CharField(blank=True, max_length=200)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('current_step', models.PositiveIntegerField(default=0)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('approver', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Returned', 'Returned')], default='Pending', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='iams.approvalrequest')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
