# Generated by Django 6.0.2 on 2026-05-11 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('iams', '0004_approvalrequest_approvalstep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('In Review', 'In Review'), ('Final', 'Final')], default='Draft', max_length=20)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('reviewer', models.CharField(blank=True, max_length=200)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(blank=True, null=True)),
                ('department', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-last_modified', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditReportSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ManagedDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Policies', 'Policies'), ('Procedures', 'Procedures'), ('Standards', 'Standards'), ('Templates', 'Templates'), ('Evidence', 'Evidence'), ('Reports', 'Reports')], default='Policies', max_length=30)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Under Review', 'Under Review'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('owner', models.CharField(blank=True, max_length=200)),
                ('department', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/')),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('file_size', models.CharField(blank=True, max_length=50)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('modified_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('versions', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['-modified_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcedure',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('objective', models.TextField(blank=True)),
                ('risk_area', models.CharField(blank=True, max_length=255)),
                ('control_ref', models.CharField(blank=True, max_length=100)),
                ('assigned_to', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Reviewed', 'Reviewed')], default='Not Started', max_length=20)),
                ('conclusion', models.TextField(blank=True)),
                ('signed_off_by', models.CharField(blank=True, max_length=200)),
                ('signed_off_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='WorkProcedureStep',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('method', models.CharField(choices=[('Inquiry', 'Inquiry'), ('Observation', 'Observation'), ('Inspection', 'Inspection'), ('Re-performance', 'Re-performance'), ('Analytical', 'Analytical')], default='Inspection', max_length=20)),
                ('sample_size', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('Not Started', 'Not Started'), ('Pass', 'Pass'), ('Fail', 'Fail'), ('N/A', 'N/A'), ('Exception', 'Exception')], default='Not Started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('completed_by', models.CharField(blank=True, max_length=200)),
                ('completed_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkProgram',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='audit',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='iams.department'),
        ),
        migrations.AddField(
            model_name='audit',
            name='lead_auditor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_audits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditableentity',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditable_entities', to='iams.department'),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='actor_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_log_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlogentry',
            name='target_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='assignee_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_checklist_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments_authored', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='comment',
            name='target_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrective_actions', to='iams.department'),
        ),
        migrations.AddField(
            model_name='correctiveaction',
            name='owner_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_corrective_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidencefile',
            name='uploaded_by_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finding',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='iams.department'),
        ),
        migrations.AddField(
            model_name='finding',
            name='owner_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_findings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskhistoryentry',
            name='entity_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_history_entries', to='iams.auditableentity'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['status', 'start_date'], name='iams_audit_status_42b325_idx'),
        ),
        migrations.AddIndex(
            model_name='correctiveaction',
            index=models.Index(fields=['status', 'due_date'], name='iams_correc_status_2fc099_idx'),
        ),
        migrations.AddIndex(
            model_name='evidencefile',
            index=models.Index(fields=['audit', 'uploaded_at'], name='iams_eviden_audit_i_99a3fc_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['status', 'due_date'], name='iams_findin_status_1cc843_idx'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='iams.audit'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='author_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_reports', to='iams.department'),
        ),
        migrations.AddField(
            model_name='auditreport',
            name='reviewer_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditreportsection',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='iams.auditreport'),
        ),
        migrations.AddField(
            model_name='manageddocument',
            name='department_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_documents', to='iams.department'),
        ),
        migrations.AddField(
            model_name='manageddocument',
            name='owner_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workprocedure',
            name='assigned_to_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_work_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workprocedure',
            name='signed_off_by_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signed_off_work_procedures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workprocedurestep',
            name='completed_by_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_work_steps', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workprocedurestep',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='iams.workprocedure'),
        ),
        migrations.AddField(
            model_name='workprogram',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_programs', to='iams.audit'),
        ),
        migrations.AddField(
            model_name='workprocedure',
            name='work_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='iams.workprogram'),
        ),
    ]
