# Generated by Django 6.0.2 on 2026-05-12 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0005_auditreport_auditreportsection_manageddocument_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="riskassessmentimportissue",
            old_name="sheet_name",
            new_name="sheet",
        ),
        migrations.AddField(
            model_name="riskassessmentimportissue",
            name="cell",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
