# Generated by Django 6.0.2 on 2026-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0006_rename_sheet_name_riskassessmentimportissue_sheet_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="evidencefile",
            name="quarantined",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="scan_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("error", "Scan error"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="evidencefile",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="quarantined",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="scan_signature",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="scan_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("clean", "Clean"),
                    ("infected", "Infected"),
                    ("error", "Scan error"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="manageddocument",
            name="scanned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
