# Generated by Django 6.0.2 on 2026-05-12 11:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("iams", "0007_evidencefile_quarantined_evidencefile_scan_signature_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlogentry",
            name="changes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="request_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditlogentry",
            name="user_agent",
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="action",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="actor",
            field=models.CharField(
                help_text="Email or display name at the time of the action.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="target",
            field=models.CharField(help_text="Human label of the affected object.", max_length=255),
        ),
        migrations.AlterField(
            model_name="auditlogentry",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(fields=["-timestamp"], name="iams_auditl_timesta_962089_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["actor_ref", "-timestamp"], name="iams_auditl_actor_r_f29498_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["target_content_type", "target_object_id"],
                name="iams_auditl_target__29c0c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlogentry",
            index=models.Index(
                fields=["action", "-timestamp"], name="iams_auditl_action_4a4615_idx"
            ),
        ),
    ]
