# Generated by Django 6.0.2 on 2026-05-12 11:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("iams", "0009_auditlogentry_immutability_trigger"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audit_assigned", "Audit assigned"),
                            ("audit_status_change", "Audit status changed"),
                            ("finding_raised", "Finding raised"),
                            ("cap_assigned", "CAP assigned"),
                            ("cap_due_soon", "CAP due in 3 days"),
                            ("cap_overdue", "CAP overdue"),
                            ("approval_requested", "Approval requested"),
                            ("approval_approved", "Approval approved"),
                            ("approval_rejected", "Approval rejected"),
                            ("password_reset", "Password reset"),
                            ("file_quarantine", "File quarantined"),
                            ("weekly_digest", "Weekly digest"),
                            ("mfa_reminder", "MFA setup reminder"),
                            ("generic", "Generic"),
                        ],
                        max_length=40,
                    ),
                ),
                ("in_app_enabled", models.BooleanField(default=True)),
                ("email_enabled", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["user_id", "kind"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="email_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("audit_assigned", "Audit assigned"),
                    ("audit_status_change", "Audit status changed"),
                    ("finding_raised", "Finding raised"),
                    ("cap_assigned", "CAP assigned"),
                    ("cap_due_soon", "CAP due in 3 days"),
                    ("cap_overdue", "CAP overdue"),
                    ("approval_requested", "Approval requested"),
                    ("approval_approved", "Approval approved"),
                    ("approval_rejected", "Approval rejected"),
                    ("password_reset", "Password reset"),
                    ("file_quarantine", "File quarantined"),
                    ("weekly_digest", "Weekly digest"),
                    ("mfa_reminder", "MFA setup reminder"),
                    ("generic", "Generic"),
                ],
                db_index=True,
                default="generic",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name="notification",
            name="module",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="notification",
            name="recipient",
            field=models.ForeignKey(
                blank=True,
                help_text="Specific recipient. NULL = system-wide broadcast.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_content_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_object_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="read",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[("info", "Info"), ("warning", "Warning"), ("action", "Action required")],
                default="info",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["recipient", "read", "-timestamp"], name="iams_notifi_recipie_3febe7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["kind", "-timestamp"], name="iams_notifi_kind_9064b5_idx"),
        ),
        migrations.AddField(
            model_name="notificationpreference",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_preferences",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="notificationpreference",
            constraint=models.UniqueConstraint(
                fields=("user", "kind"), name="iams_notif_pref_user_kind_unique"
            ),
        ),
    ]
