# Generated by Django 6.0.2 on 2026-05-12 12:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0010_notificationpreference_notification_email_sent_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="last_action_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="due_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="escalated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="approvalstep",
            name="sla_days",
            field=models.PositiveIntegerField(
                default=7, help_text="How long this step has before it's eligible for escalation."
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="reference_id",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Returned", "Returned"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("Audit Plan", "Audit Plan"),
                    ("Finding", "Finding"),
                    ("CAP Closure", "CAP Closure"),
                    ("Report", "Report"),
                    ("Risk Assessment", "Risk Assessment"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="approver",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="role",
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="approvalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Returned", "Returned"),
                ],
                db_index=True,
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ApprovalChainTemplate",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("Audit Plan", "Audit Plan"),
                            ("Finding", "Finding"),
                            ("CAP Closure", "CAP Closure"),
                            ("Report", "Report"),
                            ("Risk Assessment", "Risk Assessment"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "chain",
                    models.JSONField(
                        default=list, help_text="Ordered list of {role, sla_days} step descriptors."
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["request_type", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("request_type",),
                        name="iams_one_active_chain_per_type",
                    )
                ],
            },
        ),
    ]
