# Generated by Django 6.0.2 on 2026-05-12 12:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0011_approvalrequest_last_action_at_approvalstep_due_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkingPaper",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Human reference, e.g. 'WP-001'. Optional; system-generated if blank.",
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="working-papers/%Y/%m/%d/"),
                ),
                ("file_type", models.CharField(blank=True, max_length=20)),
                ("file_size_kb", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Under Review", "Under Review"),
                            ("Signed", "Signed"),
                            ("Archived", "Archived"),
                        ],
                        db_index=True,
                        default="Draft",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current_version", models.BooleanField(db_index=True, default=True)),
                ("auditor_signed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_signed_at", models.DateTimeField(blank=True, null=True)),
                ("signed_off_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("clean", "Clean"),
                            ("infected", "Infected"),
                            ("error", "Scan error"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("scan_signature", models.CharField(blank=True, max_length=255)),
                ("scanned_at", models.DateTimeField(blank=True, null=True)),
                ("quarantined", models.BooleanField(db_index=True, default=False)),
                ("searchable_text", models.TextField(blank=True)),
                (
                    "audit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="working_papers",
                        to="iams.audit",
                    ),
                ),
                (
                    "auditor_signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="auditor_signed_working_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "findings",
                    models.ManyToManyField(
                        blank=True, related_name="working_papers", to="iams.finding"
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="successors",
                        to="iams.workingpaper",
                    ),
                ),
                (
                    "reviewer_signed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewer_signed_working_papers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["audit_id", "reference", "-version"],
                "indexes": [
                    models.Index(
                        fields=["audit", "is_current_version"],
                        name="iams_workin_audit_i_9f7a3f_idx",
                    ),
                    models.Index(fields=["audit", "status"], name="iams_workin_audit_i_a6a4fb_idx"),
                    models.Index(fields=["reference"], name="iams_workin_referen_56f087_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current_version", True)),
                        fields=("audit", "reference"),
                        name="iams_wp_one_current_per_audit_ref",
                    )
                ],
            },
        ),
    ]
