# Generated by Django 6.0.2 on 2026-05-12 12:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0012_workingpaper"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditKPI",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kpi_type",
                    models.CharField(
                        choices=[
                            ("timeliness", "Timeliness"),
                            ("quality", "Quality"),
                            ("coverage", "Coverage"),
                            ("budget_adherence", "Budget Adherence"),
                            ("response_rate", "Response Rate"),
                            ("report_cycle_days", "Report Cycle (days)"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        db_index=True,
                        help_text="Free-form period label (e.g. '2026-Q1', 'FY2026').",
                        max_length=32,
                    ),
                ),
                ("target", models.DecimalField(decimal_places=2, max_digits=10)),
                ("actual", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit",
                    models.CharField(blank=True, help_text="%, days, count, …", max_length=20),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("higher_is_better", "Higher is better"),
                            ("lower_is_better", "Lower is better"),
                        ],
                        default="higher_is_better",
                        help_text="Determines whether positive variance is good or bad.",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-period", "kpi_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kpi_type", "period"), name="iams_qaip_kpi_kind_period_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QAIPAssessment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("internal", "Internal"),
                            ("external", "External"),
                            ("peer", "Peer"),
                            ("post_engagement", "Post-engagement"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        db_index=True,
                        help_text="Free-form period label (e.g. '2026', '2026-Q1', 'External-2026').",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                (
                    "rating_overall",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("satisfactory", "Satisfactory"),
                            ("needs_improvement", "Needs Improvement"),
                            ("unsatisfactory", "Unsatisfactory"),
                        ],
                        help_text="Set when status moves to Completed.",
                        max_length=20,
                    ),
                ),
                ("scope", models.TextField(blank=True)),
                ("methodology", models.TextField(blank=True)),
                ("summary", models.TextField(blank=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "lead_reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qaip_assessments_led",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period", "type"],
            },
        ),
        migrations.CreateModel(
            name="QAIPFinding",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("high", "High"),
                            ("medium", "Medium"),
                            ("low", "Low"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                ("root_cause", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=200)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="findings",
                        to="iams.qaipassessment",
                    ),
                ),
                (
                    "owner_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qaip_findings_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["assessment_id", "rating", "due_date"],
            },
        ),
        migrations.CreateModel(
            name="StakeholderSurvey",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "respondent_role",
                    models.CharField(
                        choices=[
                            ("auditee", "Auditee"),
                            ("department_head", "Department Head"),
                            ("executive", "Executive"),
                            ("board_member", "Board Member"),
                            ("audit_committee", "Audit Committee"),
                            ("external_auditor", "External Auditor"),
                            ("other", "Other"),
                        ],
                        default="auditee",
                        max_length=32,
                    ),
                ),
                (
                    "satisfaction_score",
                    models.PositiveSmallIntegerField(
                        help_text="1 (very dissatisfied) to 5 (very satisfied)."
                    ),
                ),
                ("feedback", models.TextField(blank=True)),
                ("anonymous", models.BooleanField(db_index=True, default=False)),
                ("submitted_at", models.DateTimeField()),
                (
                    "audit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stakeholder_surveys",
                        to="iams.audit",
                    ),
                ),
                (
                    "respondent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Cleared automatically when anonymous=True.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="qaip_survey_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="qaipassessment",
            index=models.Index(fields=["type", "period"], name="iams_qaipas_type_3da697_idx"),
        ),
        migrations.AddIndex(
            model_name="qaipassessment",
            index=models.Index(fields=["status", "-period"], name="iams_qaipas_status_50701f_idx"),
        ),
        migrations.AddIndex(
            model_name="stakeholdersurvey",
            index=models.Index(
                fields=["audit", "-submitted_at"], name="iams_stakeh_audit_i_7e2a44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stakeholdersurvey",
            index=models.Index(
                fields=["respondent_role", "-submitted_at"], name="iams_stakeh_respond_868a8a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stakeholdersurvey",
            constraint=models.CheckConstraint(
                condition=models.Q(("satisfaction_score__gte", 1), ("satisfaction_score__lte", 5)),
                name="iams_qaip_survey_score_range",
            ),
        ),
    ]
