# Generated by Django 6.0.2 on 2026-05-12 13:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0013_auditkpi_qaipassessment_qaipfinding_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CSAQuestionnaire",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("COSO", "COSO"),
                            ("COBIT", "COBIT"),
                            ("ISO 27001", "ISO 27001"),
                            ("Custom", "Custom"),
                        ],
                        default="Custom",
                        max_length=30,
                    ),
                ),
                ("version", models.CharField(default="1.0", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "weak_threshold",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Score (0-100) below which a response is flagged as a weak control.",
                    ),
                ),
            ],
            options={
                "ordering": ["-version", "title"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("title", "version"),
                        name="iams_csa_questionnaire_title_version_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CSAQuestion",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        blank=True,
                        help_text="Free-form control reference (e.g. 'COSO-CC1.1').",
                        max_length=50,
                    ),
                ),
                ("text", models.TextField()),
                (
                    "response_type",
                    models.CharField(
                        choices=[
                            ("yes_no", "Yes / No"),
                            ("scale_1_5", "Scale 1-5"),
                            ("text", "Free text"),
                            ("evidence_required", "Free text + evidence file"),
                        ],
                        default="yes_no",
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "General"),
                            ("design", "Control design"),
                            ("operating", "Operating effectiveness"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1, help_text="Relative weight in the final score (must be ≥ 1)."
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="iams.csaquestionnaire",
                    ),
                ),
            ],
            options={
                "ordering": ["questionnaire_id", "order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSAResponse",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("department", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("score_overall", models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                (
                    "score_design",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                (
                    "score_operating",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("is_weak", models.BooleanField(db_index=True, default=False)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csa_responses",
                        to="iams.auditableentity",
                    ),
                ),
                (
                    "questionnaire",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="iams.csaquestionnaire",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csa_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CSAAnswer",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("value", models.TextField(blank=True)),
                (
                    "challenge_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "None"), ("open", "Open"), ("resolved", "Resolved")],
                        db_index=True,
                        default="",
                        max_length=20,
                    ),
                ),
                ("challenge_note", models.TextField(blank=True)),
                ("challenged_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "challenged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csa_challenges_opened",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "evidence_file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csa_answers",
                        to="iams.evidencefile",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="csa_challenges_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="answers",
                        to="iams.csaquestion",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="iams.csaresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["response_id", "question__order"],
            },
        ),
        migrations.AddIndex(
            model_name="csaquestion",
            index=models.Index(
                fields=["questionnaire", "order"], name="iams_csaque_questio_263f27_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csaresponse",
            index=models.Index(
                fields=["questionnaire", "status"], name="iams_csares_questio_efe5e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="csaresponse",
            index=models.Index(
                fields=["entity", "-submitted_at"], name="iams_csares_entity__dd5466_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="csaanswer",
            constraint=models.UniqueConstraint(
                fields=("response", "question"), name="iams_csa_answer_response_question_unique"
            ),
        ),
    ]
