# Generated by Django 6.0.2 on 2026-05-12 13:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0014_csaquestionnaire_csaquestion_csaresponse_csaanswer_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Control",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "control_id",
                    models.CharField(
                        db_index=True,
                        help_text="Org-defined reference, e.g. 'AP-01' or 'FRC-13'.",
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "framework",
                    models.CharField(
                        choices=[
                            ("SOX", "SOX"),
                            ("COSO", "COSO"),
                            ("COBIT", "COBIT"),
                            ("Custom", "Custom"),
                        ],
                        default="SOX",
                        max_length=20,
                    ),
                ),
                (
                    "control_type",
                    models.CharField(
                        choices=[
                            ("preventive", "Preventive"),
                            ("detective", "Detective"),
                            ("corrective", "Corrective"),
                        ],
                        default="preventive",
                        max_length=20,
                    ),
                ),
                (
                    "nature",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("automated", "Automated"),
                            ("hybrid", "Hybrid (IT-dependent manual)"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("annual", "Annual"),
                            ("ad_hoc", "Ad hoc"),
                        ],
                        default="monthly",
                        max_length=20,
                    ),
                ),
                (
                    "assertion",
                    models.CharField(
                        blank=True,
                        help_text="Financial-statement assertion: existence, completeness, accuracy, valuation, …",
                        max_length=100,
                    ),
                ),
                ("risk_rating", models.CharField(default="Medium", max_length=20)),
                ("owner", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("retired", "Retired")],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="icfr_controls",
                        to="iams.auditableentity",
                    ),
                ),
                (
                    "owner_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icfr_controls_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["entity_id", "control_id"],
            },
        ),
        migrations.CreateModel(
            name="ControlTest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "period",
                    models.CharField(db_index=True, help_text="e.g. 'FY2026-Q1'.", max_length=32),
                ),
                (
                    "test_type",
                    models.CharField(
                        choices=[
                            ("design", "Test of Design"),
                            ("operating", "Test of Operating Effectiveness"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        db_index=True,
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("planned_sample_size", models.PositiveIntegerField(default=0)),
                ("sample_size", models.PositiveIntegerField(default=0)),
                ("sample_method", models.CharField(blank=True, max_length=100)),
                (
                    "management_assessment",
                    models.CharField(
                        choices=[
                            ("not_tested", "Not Tested"),
                            ("effective", "Effective"),
                            ("deficient", "Deficient"),
                        ],
                        default="not_tested",
                        help_text="Process owner's self-assessment.",
                        max_length=20,
                    ),
                ),
                ("management_assessment_notes", models.TextField(blank=True)),
                (
                    "auditor_assessment",
                    models.CharField(
                        choices=[
                            ("not_tested", "Not Tested"),
                            ("effective", "Effective"),
                            ("deficient", "Deficient"),
                        ],
                        default="not_tested",
                        help_text="Independent IA conclusion. Takes precedence in summary reports.",
                        max_length=20,
                    ),
                ),
                ("auditor_assessment_notes", models.TextField(blank=True)),
                ("started_at", models.DateField(blank=True, null=True)),
                ("completed_at", models.DateField(blank=True, null=True)),
                (
                    "control",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tests",
                        to="iams.control",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icfr_tests_reviewed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tester",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icfr_tests_run",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["control_id", "-period", "test_type"],
            },
        ),
        migrations.CreateModel(
            name="ControlException",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "sample_ref",
                    models.CharField(
                        blank=True,
                        help_text="Sample identifier — e.g. transaction ID or document number.",
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("identified_at", models.DateField(blank=True, null=True)),
                (
                    "evidence_files",
                    models.ManyToManyField(
                        blank=True, related_name="icfr_exceptions", to="iams.evidencefile"
                    ),
                ),
                (
                    "test",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exceptions",
                        to="iams.controltest",
                    ),
                ),
            ],
            options={
                "ordering": ["test_id", "-identified_at"],
            },
        ),
        migrations.CreateModel(
            name="DeficiencyReport",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "classification",
                    models.CharField(
                        choices=[
                            ("control_deficiency", "Control Deficiency"),
                            ("significant_deficiency", "Significant Deficiency"),
                            ("material_weakness", "Material Weakness"),
                        ],
                        db_index=True,
                        default="control_deficiency",
                        max_length=30,
                    ),
                ),
                ("narrative", models.TextField(blank=True)),
                ("recommendation", models.TextField(blank=True)),
                ("management_response", models.TextField(blank=True)),
                ("identified_date", models.DateField(blank=True, null=True)),
                ("target_resolution_date", models.DateField(blank=True, null=True)),
                ("actual_resolution_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("remediating", "Remediating"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=200)),
                (
                    "owner_ref",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="icfr_deficiencies_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deficiency",
                        to="iams.controltest",
                    ),
                ),
            ],
            options={
                "ordering": ["-identified_date", "classification"],
            },
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(
                fields=["framework", "control_type"], name="iams_contro_framewo_370cb9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="control",
            index=models.Index(
                fields=["status", "risk_rating"], name="iams_contro_status_904db5_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="control",
            constraint=models.UniqueConstraint(
                fields=("entity", "control_id"), name="iams_icfr_control_entity_ref_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="controltest",
            index=models.Index(fields=["period", "status"], name="iams_contro_period_2126d4_idx"),
        ),
        migrations.AddIndex(
            model_name="controltest",
            index=models.Index(
                fields=["auditor_assessment"], name="iams_contro_auditor_2d7c2e_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="controltest",
            constraint=models.UniqueConstraint(
                fields=("control", "period", "test_type"),
                name="iams_icfr_test_control_period_type_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="controlexception",
            index=models.Index(fields=["test", "severity"], name="iams_contro_test_id_1dd7a3_idx"),
        ),
        migrations.AddIndex(
            model_name="deficiencyreport",
            index=models.Index(
                fields=["classification", "status"], name="iams_defici_classif_43b9de_idx"
            ),
        ),
    ]
