# Generated by Django 6.0.2 on 2026-05-12 15:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0015_control_controltest_controlexception_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("scale_min", models.PositiveSmallIntegerField(default=1)),
                ("scale_max", models.PositiveSmallIntegerField(default=5)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("scale_max__gt", models.F("scale_min"))),
                        name="iams_risk_factor_scale_min_lt_max",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RiskFactorWeight",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("weight", models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                (
                    "factor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="weights",
                        to="iams.riskfactor",
                    ),
                ),
            ],
            options={
                "ordering": ["scoring_model_id", "factor__name"],
            },
        ),
        migrations.CreateModel(
            name="RiskScoringModel",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("description", models.TextField(blank=True)),
                (
                    "formula",
                    models.CharField(
                        choices=[
                            ("weighted_sum", "Weighted sum"),
                            ("weighted_avg", "Weighted average"),
                            ("multiplicative", "Multiplicative (likelihood × impact)"),
                        ],
                        default="weighted_sum",
                        max_length=30,
                    ),
                ),
                (
                    "high_risk_threshold",
                    models.DecimalField(decimal_places=2, default=70, max_digits=5),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                (
                    "factors",
                    models.ManyToManyField(
                        related_name="scoring_models",
                        through="iams.RiskFactorWeight",
                        to="iams.riskfactor",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "-version"],
            },
        ),
        migrations.AddField(
            model_name="riskfactorweight",
            name="scoring_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="factor_weights",
                to="iams.riskscoringmodel",
            ),
        ),
        migrations.CreateModel(
            name="EntityRiskScore",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("factor_values", models.JSONField(default=dict)),
                ("composite_score", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("rank", models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ("is_high_risk", models.BooleanField(db_index=True, default=False)),
                ("is_current", models.BooleanField(db_index=True, default=True)),
                ("snapshot_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_scores",
                        to="iams.auditableentity",
                    ),
                ),
                (
                    "snapshot_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_snapshots_taken",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scoring_model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entity_scores",
                        to="iams.riskscoringmodel",
                    ),
                ),
            ],
            options={
                "ordering": ["-snapshot_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="riskscoringmodel",
            constraint=models.UniqueConstraint(
                fields=("name", "version"), name="iams_risk_model_name_version_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="riskscoringmodel",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("name",),
                name="iams_risk_model_one_active_per_name",
            ),
        ),
        migrations.AddConstraint(
            model_name="riskfactorweight",
            constraint=models.UniqueConstraint(
                fields=("scoring_model", "factor"),
                name="iams_risk_factor_weight_model_factor_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="entityriskscore",
            index=models.Index(
                fields=["entity", "scoring_model", "-snapshot_at"],
                name="iams_entity_entity__ee2b64_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityriskscore",
            index=models.Index(
                fields=["scoring_model", "is_current", "-composite_score"],
                name="iams_entity_scoring_f4dec7_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityriskscore",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("entity", "scoring_model"),
                name="iams_entity_risk_score_one_current",
            ),
        ),
    ]
