# Generated by Django 6.0.2 on 2026-05-12 15:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0016_riskfactor_riskfactorweight_riskscoringmodel_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("audit_summary", "Audit Summary"),
                            ("finding_trends", "Finding Trends"),
                            ("cap_status", "CAP Status"),
                            ("department_risk_profile", "Department Risk Profile"),
                            ("open_issues", "Open Issues"),
                            ("annual_audit_plan", "Annual Audit Plan"),
                            ("icfr_summary", "ICFR Summary"),
                            ("qaip_annual", "QAIP Annual"),
                            ("audit_committee_pack", "Audit Committee Pack"),
                            ("findings_excel", "Findings Export (Excel)"),
                            ("caps_excel", "CAPs Export (Excel)"),
                            ("time_entries_excel", "Time Entries Export (Excel)"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "output_format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("xlsx", "Excel")], default="pdf", max_length=10
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("parameters", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "output_file",
                    models.FileField(blank=True, null=True, upload_to="reports/%Y/%m/%d/"),
                ),
                ("file_size_kb", models.PositiveIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="report_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["requested_by", "-created_at"],
                        name="iams_report_request_501442_idx",
                    ),
                    models.Index(
                        fields=["kind", "status", "-created_at"], name="iams_report_kind_385c0a_idx"
                    ),
                ],
            },
        ),
    ]
