# Generated by Django 6.0.2 on 2026-05-13 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0017_reportjob"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="mfa_required",
            field=models.BooleanField(
                default=False, help_text="Force MFA enrollment for every user with this role."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_activity_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_login_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AccountLockout",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("failed_attempts", "Failed attempt threshold"),
                            ("admin_action", "Administrative action"),
                            ("suspected_compromise", "Suspected compromise"),
                        ],
                        default="failed_attempts",
                        max_length=40,
                    ),
                ),
                ("locked_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("locked_until", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                ("failed_attempt_count", models.PositiveIntegerField(default=0)),
                ("note", models.TextField(blank=True)),
                (
                    "cleared_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lockouts_cleared",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lockouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-locked_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-locked_at"], name="iams_accoun_user_id_73b147_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("cleared_at__isnull", True)),
                        fields=("user",),
                        name="iams_account_lockout_one_active",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=255)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("invalid_credentials", "Invalid credentials"),
                            ("user_not_found", "User not found"),
                            ("user_inactive", "User inactive"),
                            ("account_locked", "Account locked"),
                            ("mfa_required", "MFA required"),
                            ("mfa_failed", "MFA failed"),
                            ("throttled", "Throttled"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=512)),
                ("request_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="login_attempts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["username", "-timestamp"], name="iams_logina_usernam_858c9c_idx"
                    ),
                    models.Index(
                        fields=["outcome", "-timestamp"], name="iams_logina_outcome_81f568_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"], name="iams_logina_ip_addr_02e189_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MFADevice",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("totp", "TOTP authenticator"), ("backup_codes", "Backup codes")],
                        default="totp",
                        max_length=20,
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, help_text="User-facing label.", max_length=100),
                ),
                (
                    "secret",
                    models.CharField(
                        help_text="Base32-encoded TOTP secret OR Fernet-encrypted backup-code JSON.",
                        max_length=255,
                    ),
                ),
                ("confirmed", models.BooleanField(db_index=True, default=False)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mfa_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "kind", "confirmed"], name="iams_mfadev_user_id_ef7418_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("confirmed", True), ("kind", "totp")),
                        fields=("user", "kind"),
                        name="iams_mfa_device_one_confirmed_totp",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PasswordHistory",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("password_hash", models.CharField(max_length=255)),
                ("set_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="password_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-set_at"],
                "indexes": [
                    models.Index(fields=["user", "-set_at"], name="iams_passwo_user_id_eeef72_idx")
                ],
            },
        ),
    ]
