# Generated by Django 6.0.2 on 2026-05-13 09:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0018_security_phase5"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(
                fields=["department", "status"], name="iams_audit_departm_f66e95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["start_date"], name="iams_audit_start_d_3cf0da_idx"),
        ),
        migrations.AddIndex(
            model_name="audit",
            index=models.Index(fields=["lead_auditor"], name="iams_audit_lead_au_220a06_idx"),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(
                fields=["department", "status"], name="iams_correc_departm_7d6b1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(
                fields=["owner", "status", "due_date"], name="iams_correc_owner_d23a16_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="correctiveaction",
            index=models.Index(fields=["finding", "status"], name="iams_correc_finding_9ece92_idx"),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["department", "status"], name="iams_findin_departm_2866cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["owner", "status", "due_date"], name="iams_findin_owner_2181ba_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["severity", "status"], name="iams_findin_severit_dbda8a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(fields=["created_date"], name="iams_findin_created_a5dc03_idx"),
        ),
    ]
