# Generated by Django 6.0.2 on 2026-05-13 11:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0019_perf_indexes_phase5"),
    ]

    operations = [
        migrations.CreateModel(
            name="KeycloakGroupRoleMap",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "group_name",
                    models.CharField(
                        help_text="Full Keycloak group path, e.g. '/IAMS/Auditors'.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "precedence",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Lower wins when a user is in multiple mapped groups."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="keycloak_mappings",
                        to="iams.role",
                    ),
                ),
            ],
            options={
                "ordering": ["precedence", "group_name"],
                "indexes": [
                    models.Index(
                        fields=["group_name", "is_active"], name="iams_keyclo_group_n_15eec0_idx"
                    )
                ],
            },
        ),
    ]
