# Generated by Django 6.0.2 on 2026-05-13 11:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0020_sso_phase6"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("inbound", "Inbound"), ("outbound", "Outbound")],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        db_index=True,
                        help_text="auditable_entity | finding | user | ...",
                        max_length=40,
                    ),
                ),
                ("external_id", models.CharField(blank=True, db_index=True, max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationSource",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sap", "SAP"),
                            ("oracle", "Oracle"),
                            ("odoo", "Odoo"),
                            ("active_directory", "Active Directory"),
                            ("hris", "HRIS"),
                            ("generic", "Generic"),
                        ],
                        default="generic",
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("paused", "Paused"), ("error", "Error")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("inbound_enabled", models.BooleanField(default=False)),
                (
                    "inbound_secret",
                    models.CharField(
                        blank=True,
                        help_text="HMAC-SHA256 secret used to verify inbound webhooks.",
                        max_length=128,
                    ),
                ),
                ("outbound_enabled", models.BooleanField(default=False)),
                ("outbound_url", models.URLField(blank=True)),
                ("outbound_token", models.CharField(blank=True, max_length=512)),
                ("outbound_pushes_users", models.BooleanField(default=False)),
                ("last_inbound_at", models.DateTimeField(blank=True, null=True)),
                ("last_outbound_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="audit",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="audit",
            name="external_source",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="external_source",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="finding",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name="finding",
            name="external_source",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name="audit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_source", "external_id"),
                name="iams_audit_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditableentity",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_source", "external_id"),
                name="iams_auditable_entity_external_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="finding",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_id", ""), _negated=True),
                fields=("external_source", "external_id"),
                name="iams_finding_external_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationsource",
            index=models.Index(fields=["kind", "status"], name="iams_integr_kind_8032a3_idx"),
        ),
        migrations.AddField(
            model_name="integrationevent",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="iams.integrationsource",
            ),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(
                fields=["source", "-timestamp"], name="iams_integr_source__ed8209_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="integrationevent",
            index=models.Index(
                fields=["resource_type", "external_id"], name="iams_integr_resourc_df0185_idx"
            ),
        ),
    ]
