# Generated by Django 6.0.2 on 2026-05-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0021_integrations_phase6"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ar", "العربية"), ("fr", "Français")],
                default="en",
                help_text="Preferred UI language; restored on next login.",
                max_length=8,
            ),
        ),
    ]
