# Generated by Django 6.0.2 on 2026-05-15 10:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0022_i18n_phase6"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                ("color", models.CharField(blank=True, max_length=16)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Compliance", "Compliance"),
                            ("Regulatory", "Regulatory"),
                            ("Functional", "Functional"),
                            ("Risk", "Risk"),
                            ("Custom", "Custom"),
                        ],
                        default="Custom",
                        max_length=20,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="audit_frequency",
            field=models.CharField(
                choices=[
                    ("Annual", "Annual"),
                    ("SemiAnnual", "Semi-annual"),
                    ("Quarterly", "Quarterly"),
                    ("AdHoc", "Ad hoc"),
                    ("Continuous", "Continuous"),
                ],
                default="Annual",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="compliance_status",
            field=models.CharField(
                choices=[
                    ("Compliant", "Compliant"),
                    ("NonCompliant", "Non-compliant"),
                    ("InReview", "In review"),
                    ("NotAssessed", "Not assessed"),
                ],
                default="NotAssessed",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="cost_center_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Process", "Process"),
                    ("System", "System"),
                    ("Function", "Function"),
                    ("Project", "Project"),
                    ("ComplianceArea", "Compliance Area"),
                ],
                default="Process",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="headcount",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="inherent_impact",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="inherent_likelihood",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="is_mandatory_to_audit",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="last_audit_period",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="last_audit_rating",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Satisfactory", "Satisfactory"),
                    ("NeedsImprovement", "Needs improvement"),
                    ("Unsatisfactory", "Unsatisfactory"),
                    ("NA", "Not applicable"),
                ],
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="operating_budget",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional parent entity for hierarchy (e.g. Financial Operations → Accounts Payable Oversight).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="iams.auditableentity",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="primary_language",
            field=models.CharField(blank=True, default="en", max_length=8),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="primary_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_owned_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="secondary_owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="secondary_owned_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="department",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="risk_rating",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive"), ("Archived", "Archived")],
                default="Active",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="risk_rating",
            field=models.CharField(
                choices=[
                    ("Low", "Low"),
                    ("Medium", "Medium"),
                    ("High", "High"),
                    ("Critical", "Critical"),
                ],
                default="Medium",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="AuditableEntityRevision",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "changes",
                    models.JSONField(
                        default=dict,
                        help_text='Field-level diff: {"field": {"from": <old>, "to": <new>}}.',
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entity_revisions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="iams.auditableentity",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BusinessUnit",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(blank=True, db_index=True, max_length=32)),
                (
                    "risk_appetite",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "head",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="led_business_units",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="iams.businessunit",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="auditable_entities",
                to="iams.businessunit",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="business_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="departments",
                to="iams.businessunit",
            ),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["parent"], name="ae_parent_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["business_unit", "status"], name="ae_bu_status_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["department_ref", "status"], name="ae_dept_status_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["risk_rating", "status"], name="ae_risk_status_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["next_audit_date"], name="ae_next_audit_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["primary_owner"], name="ae_primary_owner_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["compliance_status"], name="ae_compliance_idx"),
        ),
        migrations.AddIndex(
            model_name="auditableentityrevision",
            index=models.Index(fields=["entity", "-version"], name="ae_rev_entity_ver_idx"),
        ),
        migrations.AddConstraint(
            model_name="auditableentityrevision",
            constraint=models.UniqueConstraint(
                fields=("entity", "version"), name="iams_ae_revision_unique_version"
            ),
        ),
    ]
