# Generated by Django 6.0.2 on 2026-05-15 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0023_audit_universe_phase7"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="audit_universe/imports/%Y/%m/%d/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[("strict", "Strict"), ("lenient", "Lenient")],
                        default="lenient",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Validating", "Validating"),
                            ("Importing", "Importing"),
                            ("Completed", "Completed"),
                            ("PartialSuccess", "Partial success"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.PositiveIntegerField(default=0)),
                ("processed", models.PositiveIntegerField(default=0)),
                ("created", models.PositiveIntegerField(default=0)),
                ("updated", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                (
                    "errors",
                    models.JSONField(
                        default=list,
                        help_text='Per-row error report. Each entry: {"row": int, "field": str, "message": str}.',
                    ),
                ),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_universe_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="bij_status_created_idx")
                ],
            },
        ),
    ]
