# Generated by Django 6.0.2 on 2026-05-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0024_audit_universe_bulk_import"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditableentity",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED — use ``department_ref`` (FK). Removed in next major release.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="owner",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED — use ``primary_owner`` (FK to User). Removed in next major release.",
                max_length=200,
            ),
        ),
    ]
