# Generated by Django 6.0.2 on 2026-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0025_audit_universe_deprecate_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditableentity",
            name="estimated_man_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated audit effort in man-days.",
                max_digits=6,
                null=True,
            ),
        ),
    ]
