# Generated by Django 6.0.2 on 2026-06-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0026_auditableentity_estimated_man_days"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditableentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Process", "Process"),
                    ("Department", "Department"),
                    ("Division", "Division"),
                    ("Area", "Area"),
                    ("System", "System"),
                    ("Function", "Function"),
                    ("Project", "Project"),
                    ("ComplianceArea", "Compliance Area"),
                ],
                default="Process",
                max_length=32,
            ),
        ),
    ]
