# Generated by Django 6.0.2 on 2026-06-02 10:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0027_alter_auditableentity_entity_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditableentity",
            name="estimated_man_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated audit effort in man-days.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
