# Generated by Django 6.0.2 on 2026-06-02 14:37

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0028_alter_auditableentity_estimated_man_days"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="auditableentity",
            name="impact_is_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="likelihood_is_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="risk_rating_is_overridden",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EntityRisk",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Operational", "Operational"),
                            ("Financial", "Financial"),
                            ("Compliance", "Compliance"),
                            ("Strategic", "Strategic"),
                            ("IT/Cyber", "IT / Cyber"),
                            ("Reputational", "Reputational"),
                            ("Fraud", "Fraud"),
                        ],
                        default="Operational",
                        max_length=24,
                    ),
                ),
                (
                    "inherent_likelihood",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                (
                    "inherent_impact",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("existing_controls", models.TextField(blank=True)),
                (
                    "control_effectiveness",
                    models.CharField(
                        choices=[
                            ("Effective", "Effective"),
                            ("Partially Effective", "Partially Effective"),
                            ("Ineffective", "Ineffective"),
                            ("Not Assessed", "Not Assessed"),
                        ],
                        default="Not Assessed",
                        max_length=24,
                    ),
                ),
                (
                    "residual_likelihood",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "residual_impact",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "risk_response",
                    models.CharField(
                        choices=[
                            ("Mitigate", "Mitigate"),
                            ("Accept", "Accept"),
                            ("Transfer", "Transfer"),
                            ("Avoid", "Avoid"),
                        ],
                        default="Mitigate",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("Mitigated", "Mitigated"),
                            ("Accepted", "Accepted"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=16,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risks",
                        to="iams.auditableentity",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_entity_risks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["entity", "status"], name="entity_risk_status_idx")
                ],
            },
        ),
    ]
