# Generated by Django 6.0.2 on 2026-06-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0029_auditableentity_impact_is_overridden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditableentity",
            name="custom_fields",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
