# Generated by Django 6.0.2 on 2026-06-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0032_auditableentity_department_entity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="business_unit",
        ),
        migrations.RemoveField(
            model_name="manageddocument",
            name="department_ref",
        ),
        migrations.RemoveField(
            model_name="finding",
            name="department_ref",
        ),
        migrations.RemoveField(
            model_name="auditreport",
            name="department_ref",
        ),
        migrations.RemoveField(
            model_name="audit",
            name="department_ref",
        ),
        migrations.RemoveField(
            model_name="correctiveaction",
            name="department_ref",
        ),
        migrations.RemoveIndex(
            model_name="auditableentity",
            name="ae_dept_status_idx",
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="department",
            field=models.CharField(
                blank=True,
                help_text="Denormalized owning-department name; canonical FK is ``department_entity``.",
                max_length=200,
            ),
        ),
        migrations.RemoveField(
            model_name="auditableentity",
            name="department_ref",
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
