# Generated by Django 6.0.2 on 2026-06-29 10:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0033_drop_department_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "key"],
            },
        ),
        migrations.AddField(
            model_name="role",
            name="requires_issuance_gate",
            field=models.BooleanField(
                default=False, help_text="Scoped access only sees records after formal issuance."
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department_entity",
            field=models.ForeignKey(
                blank=True,
                help_text="Canonical owning department (Department-type AuditableEntity).",
                limit_choices_to={"entity_type": "Department"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="member_user_profiles",
                to="iams.auditableentity",
            ),
        ),
        migrations.CreateModel(
            name="RoleModuleAccess",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("full", "Full"),
                            ("approve", "Approve"),
                            ("edit", "Edit"),
                            ("read", "Read"),
                            ("none", "—"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("scoped", models.BooleanField(default=False)),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_access",
                        to="iams.module",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="module_access",
                        to="iams.role",
                    ),
                ),
            ],
            options={
                "ordering": ["role", "module"],
                "indexes": [
                    models.Index(fields=["role", "module"], name="iams_rolemo_role_id_eed0ea_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("role", "module"), name="iams_role_module_unique"
                    )
                ],
            },
        ),
    ]
