# Generated by Django 6.0.2 on 2026-07-02 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0041_auditableentityrevision_immutability_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditableentity",
            name="residual_impact",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="residual_likelihood",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
