# Generated by Django 6.0.2 on 2026-07-02 13:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0042_auditableentity_residual_position"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="riskhistoryentry",
            index=models.Index(fields=["entity_ref", "-date"], name="risk_hist_entity_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("inherent_likelihood__gte", 1), ("inherent_likelihood__lte", 5)
                ),
                name="iams_entity_risk_inherent_l_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(("inherent_impact__gte", 1), ("inherent_impact__lte", 5)),
                name="iams_entity_risk_inherent_i_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("residual_likelihood__isnull", True),
                    models.Q(("residual_likelihood__gte", 1), ("residual_likelihood__lte", 5)),
                    _connector="OR",
                ),
                name="iams_entity_risk_residual_l_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("residual_impact__isnull", True),
                    models.Q(("residual_impact__gte", 1), ("residual_impact__lte", 5)),
                    _connector="OR",
                ),
                name="iams_entity_risk_residual_i_1_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("residual_likelihood__isnull", True),
                    ("residual_likelihood__lte", models.F("inherent_likelihood")),
                    _connector="OR",
                ),
                name="iams_entity_risk_residual_l_lte_inherent",
            ),
        ),
        migrations.AddConstraint(
            model_name="entityrisk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("residual_impact__isnull", True),
                    ("residual_impact__lte", models.F("inherent_impact")),
                    _connector="OR",
                ),
                name="iams_entity_risk_residual_i_lte_inherent",
            ),
        ),
    ]
