# Generated by Django 6.0.2 on 2026-07-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0044_riskhistoryentry_immutability_trigger"),
    ]

    operations = [
        migrations.AddField(
            model_name="entityriskscore",
            name="model_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="approvalchaintemplate",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("Audit Plan", "Audit Plan"),
                    ("Finding", "Finding"),
                    ("CAP Closure", "CAP Closure"),
                    ("Report", "Report"),
                    ("Risk Assessment", "Risk Assessment"),
                    ("Risk Model Change", "Risk Model Change"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="approvalrequest",
            name="type",
            field=models.CharField(
                choices=[
                    ("Audit Plan", "Audit Plan"),
                    ("Finding", "Finding"),
                    ("CAP Closure", "CAP Closure"),
                    ("Report", "Report"),
                    ("Risk Assessment", "Risk Assessment"),
                    ("Risk Model Change", "Risk Model Change"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
