# Generated by Django 6.0.2 on 2026-07-03 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0045_entityriskscore_model_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="riskassessmentrecord",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_assessment_records",
                to="iams.auditableentity",
            ),
        ),
        migrations.AddField(
            model_name="riskassessmentrecord",
            name="entity_risk",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="risk_assessment_records",
                to="iams.entityrisk",
            ),
        ),
        migrations.CreateModel(
            name="RiskAssessmentImportJob",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("file", models.FileField(upload_to="risk_assessment/imports/%Y/%m/%d/")),
                ("file_name", models.CharField(blank=True, max_length=255)),
                (
                    "mode",
                    models.CharField(
                        choices=[("strict", "Strict"), ("lenient", "Lenient")],
                        default="lenient",
                        max_length=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Importing", "Importing"),
                            ("Completed", "Completed"),
                            ("PartialSuccess", "Partial success"),
                            ("Failed", "Failed"),
                        ],
                        db_index=True,
                        default="Pending",
                        max_length=20,
                    ),
                ),
                ("link_to_engine", models.BooleanField(default=False)),
                ("sheets_created", models.PositiveIntegerField(default=0)),
                ("records_created", models.PositiveIntegerField(default=0)),
                ("records_updated", models.PositiveIntegerField(default=0)),
                ("matrix_cells", models.PositiveIntegerField(default=0)),
                ("summary_items", models.PositiveIntegerField(default=0)),
                ("skipped", models.PositiveIntegerField(default=0)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="risk_assessment_imports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="riskassessmentimportissue",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="iams.riskassessmentimportjob",
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessmentimportjob",
            index=models.Index(fields=["status", "-created_at"], name="raij_status_created_idx"),
        ),
    ]
