# Generated by Django 6.0.2 on 2026-09-16 06:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


# ── Postgres-only GIN index on the materiality sort cache ─────────────
# ``materiality_cache`` is read for register sorting and range filters; a GIN
# index over the JSONB makes those key lookups cheap. SQLite (dev / tests)
# has no equivalent and stores JSONField as text, so the index is skipped
# there rather than failing the migration.
_GIN_SQL = (
    "CREATE INDEX IF NOT EXISTS ae_materiality_cache_gin "
    "ON iams_auditableentity USING GIN (materiality_cache jsonb_path_ops)"
)
_GIN_DROP = "DROP INDEX IF EXISTS ae_materiality_cache_gin"


def _add_gin_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_GIN_SQL)


def _drop_gin_index(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(_GIN_DROP)


class Migration(migrations.Migration):

    dependencies = [
        ("iams", "0046_riskassessmentrecord_entity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="KeySystem",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                ("vendor", models.CharField(blank=True, max_length=200)),
                (
                    "criticality",
                    models.CharField(
                        choices=[
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                            ("Critical", "Critical"),
                        ],
                        default="Medium",
                        max_length=16,
                    ),
                ),
                (
                    "hosting",
                    models.CharField(
                        choices=[
                            ("OnPrem", "On-premises"),
                            ("Cloud", "Cloud (IaaS/PaaS)"),
                            ("SaaS", "SaaS"),
                            ("Hybrid", "Hybrid"),
                        ],
                        default="OnPrem",
                        max_length=16,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="riskfactor",
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="applicable_frameworks",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Regulatory / control frameworks this unit is subject to, e.g. ["SOX", "IFRS 17"]. Replaces the retired ``compliance_status`` with an input rather than a self-declared verdict.',
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="audit_objectives",
            field=models.TextField(
                blank=True,
                help_text="What an engagement over this unit would set out to establish.",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="audit_rights_confirmed",
            field=models.BooleanField(
                default=False, help_text="Contractual right to audit has been confirmed with legal."
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="code",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Human-readable register reference, e.g. OPS-0042. Preferred bulk-import upsert key. Becomes unique + required in the v2 finalize migration.",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="estimated_cosource_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated co-source / service-provider effort, in days.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="estimated_ia_days",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Estimated in-house internal-audit effort, in days.",
                max_digits=6,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="executive_sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Senior accountable stakeholder (distinct from the process owner).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sponsored_entities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="frequency_source",
            field=models.CharField(
                choices=[
                    ("RiskBased", "Risk-based"),
                    ("Mandated", "Mandated by law or regulation"),
                    ("Policy", "Internal policy"),
                ],
                default="RiskBased",
                help_text="Whether the frequency is a risk-based choice or compelled.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="is_fraud_risk_relevant",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Standard 9.4 requires the plan to consider fraud-risk coverage.",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="is_third_party",
            field=models.BooleanField(
                default=False,
                help_text="A critical third party carried in the universe. The IIA GPG (p.10) admits these where the organization has audit rights.",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="mandate_reference",
            field=models.CharField(
                blank=True,
                help_text="Which law, regulation or policy compels coverage.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="materiality_cache",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="{metric_code: numeric value} for the latest as_of. Derived — do not edit.",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="required_skills",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='Specialist skills an engagement here needs, e.g. ["it_general_controls", "actuarial"]. Standard 9.4 requires the plan to identify the necessary human resources.',
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="scope_exclusions",
            field=models.TextField(
                blank=True, help_text="Explicitly out of scope — drives coverage-gap analysis."
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="scope_inclusions",
            field=models.TextField(
                blank=True,
                help_text="What this unit covers. Keeps neighbouring entities from overlapping.",
            ),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="third_party_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="universe_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Governance", "Governance"),
                    ("Operations", "Operations"),
                    ("Finance", "Finance"),
                    ("IT", "IT"),
                    ("Compliance", "Compliance"),
                    ("Support", "Support"),
                    ("Process", "Process"),
                    ("Advisory", "Advisory"),
                    ("ThirdParty", "Third party"),
                ],
                db_index=True,
                help_text="Top-level universe taxonomy (IIA GPG Appendix D).",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="riskfactor",
            name="display_order",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="riskfactor",
            name="group",
            field=models.CharField(
                choices=[
                    ("impact", "Impact-related"),
                    ("likelihood", "Likelihood-related"),
                    ("standalone", "Standalone"),
                ],
                db_index=True,
                default="standalone",
                help_text="Whether this factor drives impact or likelihood. The ``impact_likelihood`` formula subtotals the two groups separately before summing them (IIA GPG Appendix F).",
                max_length=12,
            ),
        ),
        migrations.AddField(
            model_name="riskfactor",
            name="guidance",
            field=models.TextField(
                blank=True,
                help_text='The considerations an assessor rates against, one per line. For "Loss / material exposure": dollar value at risk, annual operating expenses, number of transactions, impact on other areas, degree of reliance on IT.',
            ),
        ),
        migrations.AddField(
            model_name="riskfactor",
            name="rating_anchors",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='What each point on the scale means, as {"1": "...", "5": "..."}. Rendered beside each option so two assessors reading the same unit land on the same number.',
            ),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="audit_frequency",
            field=models.CharField(
                choices=[
                    ("Annual", "Annual"),
                    ("SemiAnnual", "Semi-annual"),
                    ("Quarterly", "Quarterly"),
                    ("AdHoc", "Ad hoc"),
                    ("Continuous", "Continuous"),
                    ("Biennial", "Every 2 years"),
                    ("Triennial", "Every 3 years"),
                ],
                default="Annual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="auditableentity",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("Process", "Process"),
                    ("Department", "Department"),
                    ("Division", "Division"),
                    ("Area", "Area"),
                    ("System", "System"),
                    ("Function", "Function"),
                    ("Project", "Project"),
                    ("ComplianceArea", "Compliance Area"),
                    ("LegalEntity", "Legal entity"),
                    ("Branch", "Branch / site"),
                    ("Program", "Program"),
                    ("RiskArea", "Risk area"),
                    ("ThirdParty", "Third party"),
                    ("Application", "Application"),
                ],
                default="Process",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="riskscoringmodel",
            name="formula",
            field=models.CharField(
                choices=[
                    ("weighted_sum", "Weighted sum"),
                    ("weighted_avg", "Weighted average"),
                    ("multiplicative", "Multiplicative (likelihood × impact)"),
                    (
                        "impact_likelihood",
                        "Impact + likelihood subtotals (IIA risk-factor approach)",
                    ),
                ],
                default="weighted_sum",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="AssuranceCoverage",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider_name", models.CharField(max_length=200)),
                (
                    "provider_type",
                    models.CharField(
                        choices=[
                            ("external_audit", "External audit"),
                            ("regulator", "Regulator"),
                            ("second_line", "Second line (risk / compliance)"),
                            ("soc_report", "SOC / service-organisation report"),
                            ("consultant", "Consultant"),
                            ("management_testing", "Management self-testing"),
                            ("other", "Other"),
                        ],
                        default="second_line",
                        max_length=24,
                    ),
                ),
                ("scope", models.TextField(blank=True)),
                ("last_review_date", models.DateField(blank=True, null=True)),
                ("next_review_date", models.DateField(blank=True, null=True)),
                (
                    "reliance_level",
                    models.CharField(
                        choices=[
                            ("full", "Full reliance"),
                            ("partial", "Partial reliance"),
                            ("none", "No reliance"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                (
                    "reliance_rationale",
                    models.TextField(
                        blank=True,
                        help_text="Why internal audit considers this provider's work reliable. Required whenever reliance is full or partial — a reliance decision without a documented basis is not defensible under Standard 9.5.",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assurance_coverage",
                        to="iams.auditableentity",
                    ),
                ),
            ],
            options={
                "ordering": ["entity_id", "provider_name"],
            },
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="key_systems",
            field=models.ManyToManyField(
                blank=True, related_name="auditable_entities", to="iams.keysystem"
            ),
        ),
        migrations.CreateModel(
            name="MaterialityMetricDefinition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("label", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "unit",
                    models.CharField(
                        choices=[
                            ("currency", "Currency"),
                            ("count", "Count"),
                            ("percent", "Percent"),
                            ("fte", "Full-time equivalents"),
                        ],
                        default="currency",
                        max_length=16,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        help_text="ISO-4217 code; required when unit is 'currency'.",
                        max_length=3,
                    ),
                ),
                (
                    "applies_to",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Entity types and/or universe categories this metric is offered for. Empty list = offered for every entity.",
                    ),
                ),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "feeds_factor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Risk factor this metric informs, for scoring auto-suggestions.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiality_metrics",
                        to="iams.riskfactor",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="EntityMaterialityValue",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "value",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("as_of", models.DateField(help_text="Period the figure refers to.")),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text='Where the figure came from, e.g. "GL extract FY25".',
                        max_length=120,
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="materiality_values",
                        to="iams.auditableentity",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="values",
                        to="iams.materialitymetricdefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["definition__display_order", "-as_of"],
            },
        ),
        migrations.CreateModel(
            name="StrategicObjective",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("code", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "period",
                    models.CharField(
                        blank=True,
                        help_text='Planning horizon the objective belongs to, e.g. "FY2027" or "2026-2028".',
                        max_length=32,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_strategic_objectives",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.AddField(
            model_name="auditableentity",
            name="strategic_objectives",
            field=models.ManyToManyField(
                blank=True, related_name="auditable_entities", to="iams.strategicobjective"
            ),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(
                fields=["universe_category", "status"], name="ae_category_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditableentity",
            index=models.Index(fields=["frequency_source"], name="ae_freq_source_idx"),
        ),
        migrations.AddIndex(
            model_name="assurancecoverage",
            index=models.Index(
                fields=["entity", "-last_review_date"], name="assurance_recency_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="assurancecoverage",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reliance_level", "none"),
                    models.Q(("reliance_rationale", ""), _negated=True),
                    _connector="OR",
                ),
                name="iams_assurance_reliance_needs_rationale",
            ),
        ),
        migrations.AddIndex(
            model_name="entitymaterialityvalue",
            index=models.Index(
                fields=["entity", "definition", "-as_of"], name="ent_mat_lookup_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="entitymaterialityvalue",
            constraint=models.UniqueConstraint(
                fields=("entity", "definition", "as_of"),
                name="iams_entity_materiality_unique_period",
            ),
        ),
        migrations.RunPython(
            _add_gin_index,
            _drop_gin_index,
            elidable=False,
        ),
    ]
